openapi: 3.0.0
info:
  title: Ithaka Backend API
  description: documentation for the ithaka CRM backend api
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/LIKHITHBORELA/Ithaka-Backend/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: clients
  description: endpoint for managing clients
- name: customers
  description: endpoint for managing customers for a client
- name: logins
  description: endpoint for managing client authentication
paths:
  /api/clients:
    post:
      tags:
      - clients
      summary: adds a new client acccount for the database
      description: Adds an item to the system
      operationId: apiClientsPOST
      requestBody:
        description: Added Client
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientBody'
      responses:
        "200":
          description: valid addition
          content:
            applications/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        "400":
          description: "invalid input, object invalid"
        "404":
          description: client already exists
      x-swagger-router-controller: Clients
  /api/customers/:sessionID/:clientID:
    get:
      tags:
      - customers
      summary: returns all customers for a specific client
      operationId: apiCustomerssessionIDclientIDGET
      parameters:
      - name: sessionID
        in: query
        description: a sessionID in order to check if it is a valid session
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: clientID
        in: query
        description: a valid clientID which is created upon a new entry to the database
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
                x-content-type: application/json
        "400":
          description: bad input parameter
        "401":
          description: unauthorized request
      x-swagger-router-controller: Customers
  /api/customers/:sessionID/:clientID/:customerID:
    get:
      tags:
      - customers
      summary: returns a specific customer
      operationId: apiCustomerssessionIDclientIDcustomerIDGET
      parameters:
      - name: sessionID
        in: query
        description: a sessionID in order to check if it is a valid session
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: clientID
        in: query
        description: a valid clientID which is created upon a new entry to the database
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: customerID
        in: query
        description: a valid clientID which is created upon a new entry to the database
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        "400":
          description: bad input parameter
        "401":
          description: unauthorized request
      x-swagger-router-controller: Customers
    put:
      tags:
      - customers
      summary: updates a specific customer
      operationId: apiCustomerssessionIDclientIDcustomerIDPUT
      requestBody:
        description: Added Customer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerSchema'
      responses:
        "200":
          description: valid update
          content:
            applications/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        "400":
          description: "invalid input, object invalid"
        "404":
          description: client already exists
      x-swagger-router-controller: Customers
    delete:
      tags:
      - customers
      summary: deletes a specific customer
      operationId: apiCustomerssessionIDclientIDcustomerIDDELETE
      parameters:
      - name: sessionID
        in: query
        description: a sessionID in order to check if it is a valid session
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: clientID
        in: query
        description: a valid clientID which is created upon a new entry to the database
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: customerID
        in: query
        description: a valid clientID which is created upon a new entry to the database
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: deleting a valid customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        "400":
          description: bad input parameter
        "401":
          description: unauthorized request
      x-swagger-router-controller: Customers
  /api/customers/:sessionID:
    post:
      tags:
      - customers
      summary: adds a new customer
      description: Adds a customer to the database
      operationId: apiCustomerssessionIDPOST
      requestBody:
        description: Customer to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerSchema'
      responses:
        "200":
          description: valid addition
          content:
            applications/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        "400":
          description: "invalid input, object invalid"
        "404":
          description: client already exists
      x-swagger-router-controller: Customers
  /api/logins:
    post:
      tags:
      - logins
      summary: Authenticates a client to use the webapp and gives a sessionId to go
        along with a valid login
      operationId: apiLoginsPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
      responses:
        "200":
          description: valid login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "400":
          description: bad username or password
      x-swagger-router-controller: Logins
components:
  schemas:
    ClientResponse:
      required:
      - client
      type: object
      properties:
        client:
          type: object
          example:
            name: Garden Lansdscaping LLC
            email: garden@landscaping.com
            password: billyBobsBurgers123
      example:
        client:
          name: Garden Lansdscaping LLC
          email: garden@landscaping.com
          password: billyBobsBurgers123
    ClientBody:
      required:
      - client_email
      - client_name
      - client_password
      type: object
      properties:
        name:
          type: string
          example: Garden Landscaping LLC
        email:
          type: string
          example: garden@landscaping.com
        password:
          type: string
          example: billyBobsBurgers123
    CustomerSchema:
      required:
      - address
      - clientID
      - email
      - name
      - paymentMode
      - phoneNumber
      type: object
      properties:
        clientId:
          type: string
          example: 12fafd434k
        name:
          type: string
          example: Billy Bob
        email:
          type: string
          example: billybob@gmail.com
        address:
          type: string
          example: "643 Biscuit Ave, Apt. 12, Pittsburgh, PA, USA, 16510"
        phoneNumber:
          type: string
          example: "8233238900"
        paymentMode:
          type: string
          example: Cash on Delivery
      description: Schema For a Customer Object
    CustomerResponse:
      required:
      - customer
      - sessionID
      type: object
      properties:
        customer:
          type: object
          example:
            _id: 89asd89a98a9
            clientId: 12f1fafaf12
            name: Billy Bob
            email: billybob@gmail.com
            address: "643 Biscuit Ave, Apt. 12, Pittsburgh, PA, USA, 16510"
            phoneNumber: "8233238900"
            paymentMode: Cash on Delivery
        sessionId:
          type: string
          example: 45ea4f5672f
      example:
        sessionId: 45ea4f5672f
        customer:
          _id: 89asd89a98a9
          clientId: 12f1fafaf12
          name: Billy Bob
          email: billybob@gmail.com
          address: "643 Biscuit Ave, Apt. 12, Pittsburgh, PA, USA, 16510"
          phoneNumber: "8233238900"
          paymentMode: Cash on Delivery
    LoginBody:
      required:
      - clientEmail
      - clientPassword
      type: object
      properties:
        email:
          type: string
          example: billybob@gmail.com
        password:
          type: string
          example: billyBobsBurgers123
    LoginResponse:
      required:
      - accountInfo
      - sessionId
      type: object
      properties:
        sessionId:
          type: string
          example: 7862863876ff
        accountInfo:
          type: object
          example:
            _id: 755768776afafa
            name: Billy Bob
            email: billybob@gmail.com
      example:
        accountInfo:
          _id: 755768776afafa
          name: Billy Bob
          email: billybob@gmail.com
        sessionId: 7862863876ff
